version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      rabbitmq_go_cli_net:
        aliases:
          - rabbitmq.client.local
  cons_api:
    build:
      context: ./consumer
      target: builder
    env_file: ./.env.dev
    volumes:
      - ./consumer:/go/src/app
    command: go run ./
    depends_on:
      - rabbitmq
    networks:
      rabbitmq_go_cli_net:
  prod_api:
    build:
      context: ./prod
      target: builder
    env_file: ./.env.dev
    volumes:
      - ./prod:/go/src/app
    command: go run ./
    depends_on:
      - rabbitmq
    networks:
      rabbitmq_go_cli_net:

networks:
  rabbitmq_go_cli_net: